version: '3.0'

services:

  mariadb:
    container_name: my_mariadb
    build: ./requirements/mariadb
    image: my_mariadb
    restart: always
    env_file: ./.env
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - network

  wordpress:
    container_name: my_wordpress
    build: ./requirements/wordpress/
    image: my_wordpress
    env_file: ./.env
    volumes:
      - wordpress_data:/var/www/html/wordpress
    networks:
      - network
    depends_on:
      - mariadb

  nginx:
    container_name: my_nginx
    build: ./requirements/nginx/
    image: my_nginx
    ports:
      - '443:443'
    volumes:
      - wordpress_data:/var/www/html/wordpress
    networks:
      - network
    depends_on:
      - wordpress

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${MYPATH}/my_mariadb_data
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${MYPATH}/my_wordpress_data


networks:
  network:
    driver: bridge
