FROM debian:buster

WORKDIR /root/

RUN apt-get update
RUN apt-get upgrade -y
RUN apt-get install -y vim nginx wget mariadb-server \
php-mysql php7.3-fpm php-xml openssl

RUN openssl req -newkey rsa:2048 -nodes -subj \
"/C=KR/ST=Seoul/L=Seoul/O=42seoul/OU=sashin/CN=localhost" -keyout sashin-ssl.key -out sashin-ssl.csr
RUN openssl x509 -req -days 365 -in sashin-ssl.csr -signkey sashin-ssl.key -out sashin-ssl.crt
RUN mv sashin-ssl.key /etc/ssl/private/
RUN mv sashin-ssl.crt /etc/ssl/certs/

COPY ./src/default /etc/nginx/sites-available/
COPY ./src/phpinfo.php /var/www/html/
COPY ./src/set_mysql.sql /root/
COPY ./src/init.sh /root/

RUN wget https://files.phpmyadmin.net/phpMyAdmin/5.1.0/phpMyAdmin-5.1.0-all-languages.tar.gz
RUN tar -xvf phpMyAdmin-5.1.0-all-languages.tar.gz
RUN mv phpMyAdmin-5.1.0-all-languages /var/www/html/phpmyadmin
RUN rm -rf phpMyAdmin-5.1.0-all-languages.tar.gz
COPY ./src/config.inc.php /var/www/html/phpmyadmin/

RUN wget https://ko.wordpress.org/latest-ko_KR.tar.gz
RUN tar -xvf latest-ko_KR.tar.gz
RUN mv wordpress /var/www/html/wordpress
RUN rm -rf latest-ko_KR.tar.gz
COPY ./src/wp-config.php /var/www/html/wordpress/

ENTRYPOINT [ "bash", "init.sh" ]